### ISSUE TITLE
Add .i3status.conf

### ISSUE THREAD

**Issue by sethwoodworth** [gangelop/dotfiles#2]
It is missing from the repo and I'm really curious how you're configuring it.

**Comment by lathan** [comment]
Hi @sethwoodworth 

`.i3status.conf` is indeed missing. The reason for this is that it varies drastically between systems. Really the only 2 things in `.i3status.conf` are the wired and wireless interfaces, and battery status if applicable. Battery status is irrelevant for desktop machines and interface names change from system to system. So, practically there's not much sense in tracking it.

**Comment by lathan** [comment]
And to actually answer your question, I just copy it from an existing system when I install a new one, then I modify it as necessary.

**Comment by lathan** [comment]
I started using i3blocks and decided to start tracking the relevant configs. I've added the laptop config (ee53f2b) and will add the desktop config. On each machine I am creating a symlink to whichever config is relevant. For example:

```
ls -l .i3/i3blocks.conf
lrwxrwxrwx 1 george george 20 Sep 28 03:08 .i3/i3blocks.conf -> i3blocks.conf-laptop
```

**Comment by lathan** [comment]
As I mentioned in my previous comment, I've added my i3blocks configuration for all my computers.  
See ee53f2b, bb54867, and eb47af2.  
So I'm closing this issue. Thanks for prompting me to be a bit less lazy. :smile:
